### ISSUE TITLE
Implement curio adapter

### ISSUE THREAD

**Issue by malinoff** [malinoff/amqproto#4]
Doesn't worth it until several testing related issues are fixed:
- [ ] `Fatal Python error: GC object already tracked`, https://github.com/pytest-dev/pytest-asyncio/issues/61
- [ ] `pytest-curio` should be able to work with the newest `curio`, https://github.com/johnnoone/pytest-curio/issues/1
- [ ] `pytest-curio` should be able to handle async (generator) fixtures, https://github.com/johnnoone/pytest-curio/issues/4

**Comment by geronimo-iia** [comment]
Hello, with the last release of pytest-curio you could use last curio version, and it should support async (generator).
I've just started to addd few test case, let me known if it's not the case.
